# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Personal Portfolio
  params:
    description: Welcome to my personal portfolio website
  menu:
    main:
      - name: About
        url: '#about'
        weight: 1
      - name: Experience
        url: '#experience'
        weight: 2
      - name: Projects
        url: '#projects'
        weight: 3
      - name: Contact
        url: '#contact'
        weight: 4

# Chinese language
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 个人作品集
  params:
    description: 欢迎访问我的个人作品集网站
  menu:
    main:
      - name: 关于
        url: '#about'
        weight: 1
      - name: 经历
        url: '#experience'
        weight: 2
      - name: 项目
        url: '#projects'
        weight: 3
      - name: 联系
        url: '#contact'
        weight: 4
